// Generated by Haxe 3.4.7
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.root {
	public class Math {
		
		public Math() {
		}
		
		
		public static readonly global::System.Random rand = new global::System.Random();
		
		public static readonly double NaN = global::System.Double.NaN;
		
	}
}


