// Generated by Haxe 3.4.7
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace haxe.root {
	public class StringBuf : global::haxe.lang.HxObject {
		
		public StringBuf(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public StringBuf() {
			global::haxe.root.StringBuf.__hx_ctor__StringBuf(this);
		}
		
		
		public static void __hx_ctor__StringBuf(global::haxe.root.StringBuf __hx_this) {
			__hx_this.b = new global::System.Text.StringBuilder();
		}
		
		
		public global::System.Text.StringBuilder b;
		
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 98:
					{
						this.b = ((global::System.Text.StringBuilder) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 98:
					{
						return this.b;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array<object> baseArr) {
			baseArr.push("length");
			baseArr.push("b");
			base.__hx_getFields(baseArr);
		}
		
		
	}
}


