// Generated by Haxe 3.4.7
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace glm {
	public class Mat2 : global::haxe.lang.HxObject {
		
		public Mat2(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Mat2(global::haxe.lang.Null<double> _r0c0, global::haxe.lang.Null<double> _r0c1, global::haxe.lang.Null<double> _r1c0, global::haxe.lang.Null<double> _r1c1) {
			global::glm.Mat2.__hx_ctor_glm_Mat2(this, _r0c0, _r0c1, _r1c0, _r1c1);
		}
		
		
		public static void __hx_ctor_glm_Mat2(global::glm.Mat2 __hx_this, global::haxe.lang.Null<double> _r0c0, global::haxe.lang.Null<double> _r0c1, global::haxe.lang.Null<double> _r1c0, global::haxe.lang.Null<double> _r1c1) {
			double __temp__r1c111 = ( ( ! (_r1c1.hasValue) ) ? (((double) (0) )) : ((_r1c1).@value) );
			double __temp__r1c010 = ( ( ! (_r1c0.hasValue) ) ? (((double) (0) )) : ((_r1c0).@value) );
			double __temp__r0c19 = ( ( ! (_r0c1.hasValue) ) ? (((double) (0) )) : ((_r0c1).@value) );
			double __temp__r0c08 = ( ( ! (_r0c0.hasValue) ) ? (((double) (0) )) : ((_r0c0).@value) );
			__hx_this._00 = __temp__r0c08;
			__hx_this._01 = __temp__r1c010;
			__hx_this._10 = __temp__r0c19;
			__hx_this._11 = __temp__r1c111;
		}
		
		
		public static global::glm.Mat2 identity(global::glm.Mat2 dest) {
			unchecked {
				dest._00 = ((double) (1) );
				dest._10 = ((double) (0) );
				dest._01 = ((double) (0) );
				dest._11 = ((double) (1) );
				return dest;
			}
		}
		
		
		public static global::glm.Mat2 copy(global::glm.Mat2 src, global::glm.Mat2 dest) {
			dest._00 = src._00;
			dest._10 = src._10;
			dest._01 = src._01;
			dest._11 = src._11;
			return dest;
		}
		
		
		public static global::glm.Mat2 transpose(global::glm.Mat2 src, global::glm.Mat2 dest) {
			double src_r1c0 = src._01;
			dest._00 = src._00;
			dest._01 = src._10;
			dest._10 = src_r1c0;
			dest._11 = src._11;
			return dest;
		}
		
		
		public static double determinant(global::glm.Mat2 src) {
			return ( ( src._00 * src._11 ) - ( src._10 * src._01 ) );
		}
		
		
		public static global::glm.Mat2 invert(global::glm.Mat2 src, global::glm.Mat2 dest) {
			double det = ( ( src._00 * src._11 ) - ( src._10 * src._01 ) );
			if (( global::System.Math.Abs(((double) (det) )) < global::glm.GLM.EPSILON )) {
				throw global::haxe.lang.HaxeException.wrap("determinant is too small");
			}
			
			double invdet = ( 1.0 / det );
			global::glm.Mat2 _s = src;
			if (( src == dest )) {
				global::glm.Mat2 dest1 = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest1._00 = src._00;
				dest1._10 = src._10;
				dest1._01 = src._01;
				dest1._11 = src._11;
				_s = dest1;
			}
			
			dest._00 = ( _s._11 * invdet );
			dest._10 = (  - (_s._10)  * invdet );
			dest._01 = (  - (_s._01)  * invdet );
			dest._11 = ( _s._00 * invdet );
			return dest;
		}
		
		
		public static global::glm.Mat2 multMat(global::glm.Mat2 a, global::glm.Mat2 b, global::glm.Mat2 dest) {
			global::glm.Mat2 _a = null;
			global::glm.Mat2 _b = null;
			if (( dest == a )) {
				global::glm.Mat2 dest1 = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest1._00 = a._00;
				dest1._10 = a._10;
				dest1._01 = a._01;
				dest1._11 = a._11;
				_a = dest1;
				_b = b;
			}
			else if (( dest == b )) {
				_a = a;
				global::glm.Mat2 dest2 = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest2._00 = b._00;
				dest2._10 = b._10;
				dest2._01 = b._01;
				dest2._11 = b._11;
				_b = dest2;
			}
			else {
				_a = a;
				_b = b;
			}
			
			dest._00 = ( ( _a._00 * _b._00 ) + ( _a._10 * _b._01 ) );
			dest._10 = ( ( _a._00 * _b._10 ) + ( _a._10 * _b._11 ) );
			dest._01 = ( ( _a._01 * _b._00 ) + ( _a._11 * _b._01 ) );
			dest._11 = ( ( _a._01 * _b._10 ) + ( _a._11 * _b._11 ) );
			return dest;
		}
		
		
		public static global::glm.Mat2 multMatOp(global::glm.Mat2 a, global::glm.Mat2 b) {
			global::glm.Mat2 dest = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			global::glm.Mat2 _a = null;
			global::glm.Mat2 _b = null;
			if (( dest == a )) {
				global::glm.Mat2 dest1 = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest1._00 = a._00;
				dest1._10 = a._10;
				dest1._01 = a._01;
				dest1._11 = a._11;
				_a = dest1;
				_b = b;
			}
			else if (( dest == b )) {
				_a = a;
				global::glm.Mat2 dest2 = new global::glm.Mat2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest2._00 = b._00;
				dest2._10 = b._10;
				dest2._01 = b._01;
				dest2._11 = b._11;
				_b = dest2;
			}
			else {
				_a = a;
				_b = b;
			}
			
			dest._00 = ( ( _a._00 * _b._00 ) + ( _a._10 * _b._01 ) );
			dest._10 = ( ( _a._00 * _b._10 ) + ( _a._10 * _b._11 ) );
			dest._01 = ( ( _a._01 * _b._00 ) + ( _a._11 * _b._01 ) );
			dest._11 = ( ( _a._01 * _b._10 ) + ( _a._11 * _b._11 ) );
			return dest;
		}
		
		
		public static global::glm.Vec2 multVec(global::glm.Mat2 m, global::glm.Vec2 v, global::glm.Vec2 dest) {
			double x = v.x;
			double y = v.y;
			dest.x = ( ( m._00 * x ) + ( m._10 * y ) );
			dest.y = ( ( m._01 * x ) + ( m._11 * y ) );
			return dest;
		}
		
		
		public static global::glm.Vec2 multVecOp(global::glm.Mat2 m, global::glm.Vec2 v) {
			global::glm.Vec2 dest = new global::glm.Vec2(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			double x = v.x;
			double y = v.y;
			dest.x = ( ( m._00 * x ) + ( m._10 * y ) );
			dest.y = ( ( m._01 * x ) + ( m._11 * y ) );
			return dest;
		}
		
		
		public static global::glm.Mat2 fromFloatArray(global::haxe.root.Array<double> arr) {
			unchecked {
				return new global::glm.Mat2(new global::haxe.lang.Null<double>(arr[0], true), new global::haxe.lang.Null<double>(arr[2], true), new global::haxe.lang.Null<double>(arr[1], true), new global::haxe.lang.Null<double>(arr[3], true));
			}
		}
		
		
		public double _00;
		
		public double _10;
		
		public double _01;
		
		public double _11;
		
		
		
		public double get_r0c0() {
			return this._00;
		}
		
		
		public double set_r0c0(double v) {
			return this._00 = v;
		}
		
		
		
		
		public double get_r1c0() {
			return this._01;
		}
		
		
		public double set_r1c0(double v) {
			return this._01 = v;
		}
		
		
		
		
		public double get_r0c1() {
			return this._10;
		}
		
		
		public double set_r0c1(double v) {
			return this._10 = v;
		}
		
		
		
		
		public double get_r1c1() {
			return this._11;
		}
		
		
		public double set_r1c1(double v) {
			return this._11 = v;
		}
		
		
		public double @get(int key) {
			unchecked {
				switch (key) {
					case 0:
					{
						return this._00;
					}
					
					
					case 1:
					{
						return this._01;
					}
					
					
					case 2:
					{
						return this._10;
					}
					
					
					case 3:
					{
						return this._11;
					}
					
					
					default:
					{
						throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Index ", global::haxe.lang.Runtime.toString(key)), " out of bounds (0-3)!"));
					}
					
				}
				
			}
		}
		
		
		public double arrayWrite(int key, double @value) {
			unchecked {
				switch (key) {
					case 0:
					{
						return this._00 = @value;
					}
					
					
					case 1:
					{
						return this._01 = @value;
					}
					
					
					case 2:
					{
						return this._10 = @value;
					}
					
					
					case 3:
					{
						return this._11 = @value;
					}
					
					
					default:
					{
						throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Index ", global::haxe.lang.Runtime.toString(key)), " out of bounds (0-3)!"));
					}
					
				}
				
			}
		}
		
		
		public bool @equals(global::glm.Mat2 b) {
			return  ! ((( ( ( ( global::System.Math.Abs(((double) (( this._00 - b._00 )) )) >= global::glm.GLM.EPSILON ) || ( global::System.Math.Abs(((double) (( this._10 - b._10 )) )) >= global::glm.GLM.EPSILON ) ) || ( global::System.Math.Abs(((double) (( this._01 - b._01 )) )) >= global::glm.GLM.EPSILON ) ) || ( global::System.Math.Abs(((double) (( this._11 - b._11 )) )) >= global::glm.GLM.EPSILON ) ))) ;
		}
		
		
		public string toString() {
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("[", global::haxe.lang.Runtime.toString(this._00)), ", "), global::haxe.lang.Runtime.toString(this._10)), "]\n"), (global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("[", global::haxe.lang.Runtime.toString(this._01)), ", "), global::haxe.lang.Runtime.toString(this._11)), "]\n")));
		}
		
		
		public global::haxe.root.Array<double> toFloatArray() {
			return new global::haxe.root.Array<double>(new double[]{this._00, this._01, this._10, this._11});
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1266669485:
					{
						this.set_r1c1(@value);
						return @value;
					}
					
					
					case 1266619756:
					{
						this.set_r0c1(@value);
						return @value;
					}
					
					
					case 1266669484:
					{
						this.set_r1c0(@value);
						return @value;
					}
					
					
					case 1266619755:
					{
						this.set_r0c0(@value);
						return @value;
					}
					
					
					case 4735231:
					{
						this._11 = ((double) (@value) );
						return @value;
					}
					
					
					case 4735008:
					{
						this._01 = ((double) (@value) );
						return @value;
					}
					
					
					case 4735230:
					{
						this._10 = ((double) (@value) );
						return @value;
					}
					
					
					case 4735007:
					{
						this._00 = ((double) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1266669485:
					{
						this.set_r1c1(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 1266619756:
					{
						this.set_r0c1(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 1266669484:
					{
						this.set_r1c0(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 1266619755:
					{
						this.set_r0c0(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 4735231:
					{
						this._11 = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 4735008:
					{
						this._01 = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 4735230:
					{
						this._10 = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 4735007:
					{
						this._00 = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1711764408:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toFloatArray", 1711764408)) );
					}
					
					
					case 946786476:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1072885311:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "equals", 1072885311)) );
					}
					
					
					case 1250329734:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "arrayWrite", 1250329734)) );
					}
					
					
					case 5144726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 2039999658:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_r1c1", 2039999658)) );
					}
					
					
					case 1262129974:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_r1c1", 1262129974)) );
					}
					
					
					case 1266669485:
					{
						return this.get_r1c1();
					}
					
					
					case 2039949929:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_r0c1", 2039949929)) );
					}
					
					
					case 1262080245:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_r0c1", 1262080245)) );
					}
					
					
					case 1266619756:
					{
						return this.get_r0c1();
					}
					
					
					case 2039999657:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_r1c0", 2039999657)) );
					}
					
					
					case 1262129973:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_r1c0", 1262129973)) );
					}
					
					
					case 1266669484:
					{
						return this.get_r1c0();
					}
					
					
					case 2039949928:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_r0c0", 2039949928)) );
					}
					
					
					case 1262080244:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_r0c0", 1262080244)) );
					}
					
					
					case 1266619755:
					{
						return this.get_r0c0();
					}
					
					
					case 4735231:
					{
						return this._11;
					}
					
					
					case 4735008:
					{
						return this._01;
					}
					
					
					case 4735230:
					{
						return this._10;
					}
					
					
					case 4735007:
					{
						return this._00;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1266669485:
					{
						return this.get_r1c1();
					}
					
					
					case 1266619756:
					{
						return this.get_r0c1();
					}
					
					
					case 1266669484:
					{
						return this.get_r1c0();
					}
					
					
					case 1266619755:
					{
						return this.get_r0c0();
					}
					
					
					case 4735231:
					{
						return this._11;
					}
					
					
					case 4735008:
					{
						return this._01;
					}
					
					
					case 4735230:
					{
						return this._10;
					}
					
					
					case 4735007:
					{
						return this._00;
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, global::haxe.root.Array dynargs) {
			unchecked {
				switch (hash) {
					case 1711764408:
					{
						return this.toFloatArray();
					}
					
					
					case 946786476:
					{
						return this.toString();
					}
					
					
					case 1072885311:
					{
						return this.@equals(((global::glm.Mat2) (dynargs[0]) ));
					}
					
					
					case 1250329734:
					{
						return this.arrayWrite(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), ((double) (global::haxe.lang.Runtime.toDouble(dynargs[1])) ));
					}
					
					
					case 5144726:
					{
						return this.@get(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					
					case 2039999658:
					{
						return this.set_r1c1(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 1262129974:
					{
						return this.get_r1c1();
					}
					
					
					case 2039949929:
					{
						return this.set_r0c1(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 1262080245:
					{
						return this.get_r0c1();
					}
					
					
					case 2039999657:
					{
						return this.set_r1c0(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 1262129973:
					{
						return this.get_r1c0();
					}
					
					
					case 2039949928:
					{
						return this.set_r0c0(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 1262080244:
					{
						return this.get_r0c0();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array<object> baseArr) {
			baseArr.push("r1c1");
			baseArr.push("r0c1");
			baseArr.push("r1c0");
			baseArr.push("r0c0");
			baseArr.push("_11");
			baseArr.push("_01");
			baseArr.push("_10");
			baseArr.push("_00");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


