// Generated by Haxe 3.4.7
using haxe.root;

#pragma warning disable 109, 114, 219, 429, 168, 162
namespace glm {
	public class Vec3 : global::haxe.lang.HxObject {
		
		public Vec3(global::haxe.lang.EmptyObject empty) {
		}
		
		
		public Vec3(global::haxe.lang.Null<double> x, global::haxe.lang.Null<double> y, global::haxe.lang.Null<double> z) {
			global::glm.Vec3.__hx_ctor_glm_Vec3(this, x, y, z);
		}
		
		
		public static void __hx_ctor_glm_Vec3(global::glm.Vec3 __hx_this, global::haxe.lang.Null<double> x, global::haxe.lang.Null<double> y, global::haxe.lang.Null<double> z) {
			double __temp_z50 = ( ( ! (z.hasValue) ) ? (((double) (0) )) : ((z).@value) );
			double __temp_y49 = ( ( ! (y.hasValue) ) ? (((double) (0) )) : ((y).@value) );
			double __temp_x48 = ( ( ! (x.hasValue) ) ? (((double) (0) )) : ((x).@value) );
			__hx_this.x = __temp_x48;
			__hx_this.y = __temp_y49;
			__hx_this.z = __temp_z50;
		}
		
		
		public static global::glm.Vec3 copy(global::glm.Vec3 src, global::glm.Vec3 dest) {
			dest.x = src.x;
			dest.y = src.y;
			dest.z = src.z;
			return dest;
		}
		
		
		public static global::glm.Vec3 @set(global::glm.Vec3 dest, global::haxe.lang.Null<double> x, global::haxe.lang.Null<double> y, global::haxe.lang.Null<double> z) {
			double __temp_z47 = ( ( ! (z.hasValue) ) ? (((double) (0) )) : ((z).@value) );
			double __temp_y46 = ( ( ! (y.hasValue) ) ? (((double) (0) )) : ((y).@value) );
			double __temp_x45 = ( ( ! (x.hasValue) ) ? (((double) (0) )) : ((x).@value) );
			dest.x = __temp_x45;
			dest.y = __temp_y46;
			dest.z = __temp_z47;
			return dest;
		}
		
		
		public static global::glm.Vec3 addVec(global::glm.Vec3 a, global::glm.Vec3 b, global::glm.Vec3 dest) {
			dest.x = ( a.x + b.x );
			dest.y = ( a.y + b.y );
			dest.z = ( a.z + b.z );
			return dest;
		}
		
		
		public static global::glm.Vec3 subtractVec(global::glm.Vec3 a, global::glm.Vec3 b, global::glm.Vec3 dest) {
			dest.x = ( a.x - b.x );
			dest.y = ( a.y - b.y );
			dest.z = ( a.z - b.z );
			return dest;
		}
		
		
		public static global::glm.Vec3 addVecOp(global::glm.Vec3 a, global::glm.Vec3 b) {
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( a.x + b.x );
			dest.y = ( a.y + b.y );
			dest.z = ( a.z + b.z );
			return dest;
		}
		
		
		public static global::glm.Vec3 subtractVecOp(global::glm.Vec3 a, global::glm.Vec3 b) {
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( a.x - b.x );
			dest.y = ( a.y - b.y );
			dest.z = ( a.z - b.z );
			return dest;
		}
		
		
		public static global::glm.Vec3 addScalar(global::glm.Vec3 a, double s, global::glm.Vec3 dest) {
			dest.x = ( a.x + s );
			dest.y = ( a.y + s );
			dest.z = ( a.z + s );
			return dest;
		}
		
		
		public static global::glm.Vec3 multiplyScalar(global::glm.Vec3 a, double s, global::glm.Vec3 dest) {
			dest.x = ( a.x * s );
			dest.y = ( a.y * s );
			dest.z = ( a.z * s );
			return dest;
		}
		
		
		public static global::glm.Vec3 addScalarOp(global::glm.Vec3 a, double s) {
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( a.x + s );
			dest.y = ( a.y + s );
			dest.z = ( a.z + s );
			return dest;
		}
		
		
		public static global::glm.Vec3 subtractScalarOp(global::glm.Vec3 a, double s) {
			double s1 =  - (s) ;
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( a.x + s1 );
			dest.y = ( a.y + s1 );
			dest.z = ( a.z + s1 );
			return dest;
		}
		
		
		public static global::glm.Vec3 multiplyScalarOp(global::glm.Vec3 a, double s) {
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( a.x * s );
			dest.y = ( a.y * s );
			dest.z = ( a.z * s );
			return dest;
		}
		
		
		public static global::glm.Vec3 divideScalarOp(global::glm.Vec3 a, double s) {
			unchecked {
				double s1 = ( 1 / s );
				global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
				dest.x = ( a.x * s1 );
				dest.y = ( a.y * s1 );
				dest.z = ( a.z * s1 );
				return dest;
			}
		}
		
		
		public static double distanceSquared(global::glm.Vec3 a, global::glm.Vec3 b) {
			return ( ( ( (( a.x - b.x )) * (( a.x - b.x )) ) + ( (( a.y - b.y )) * (( a.y - b.y )) ) ) + ( (( a.z - b.z )) * (( a.z - b.z )) ) );
		}
		
		
		public static double distance(global::glm.Vec3 a, global::glm.Vec3 b) {
			return global::System.Math.Sqrt(((double) (( ( ( (( a.x - b.x )) * (( a.x - b.x )) ) + ( (( a.y - b.y )) * (( a.y - b.y )) ) ) + ( (( a.z - b.z )) * (( a.z - b.z )) ) )) ));
		}
		
		
		public static double angleBetween(global::glm.Vec3 a, global::glm.Vec3 b) {
			double dot = ( ( ( a.x * b.x ) + ( a.y * b.y ) ) + ( a.z * b.z ) );
			dot /= ( global::System.Math.Sqrt(((double) (( ( ( a.x * a.x ) + ( a.y * a.y ) ) + ( a.z * a.z ) )) )) * global::System.Math.Sqrt(((double) (( ( ( b.x * b.x ) + ( b.y * b.y ) ) + ( b.z * b.z ) )) )) );
			double angle = global::System.Math.Acos(((double) (dot) ));
			return angle;
		}
		
		
		public static double dot(global::glm.Vec3 a, global::glm.Vec3 b) {
			return ( ( ( a.x * b.x ) + ( a.y * b.y ) ) + ( a.z * b.z ) );
		}
		
		
		public static global::glm.Vec3 cross(global::glm.Vec3 a, global::glm.Vec3 b, global::glm.Vec3 dest) {
			dest = new global::glm.Vec3(new global::haxe.lang.Null<double>(( ( a.y * b.z ) - ( a.z * b.y ) ), true), new global::haxe.lang.Null<double>(( ( a.z * b.x ) - ( a.x * b.z ) ), true), new global::haxe.lang.Null<double>(( ( a.x * b.y ) - ( a.y * b.x ) ), true));
			return dest;
		}
		
		
		public static global::glm.Vec3 normalize(global::glm.Vec3 v, global::glm.Vec3 dest) {
			unchecked {
				double length = global::System.Math.Sqrt(((double) (( ( ( v.x * v.x ) + ( v.y * v.y ) ) + ( v.z * v.z ) )) ));
				double mult = ((double) (0) );
				if (( length >= global::glm.GLM.EPSILON )) {
					mult = ( 1 / length );
				}
				
				dest.x = ( v.x * mult );
				dest.y = ( v.y * mult );
				dest.z = ( v.z * mult );
				return dest;
			}
		}
		
		
		public static global::glm.Vec3 lerp(global::glm.Vec3 a, global::glm.Vec3 b, double t, global::glm.Vec3 dest) {
			double a1 = a.x;
			dest.x = ( a1 + ( t * (( b.x - a1 )) ) );
			double a2 = a.y;
			dest.y = ( a2 + ( t * (( b.y - a2 )) ) );
			double a3 = a.z;
			dest.z = ( a3 + ( t * (( b.z - a3 )) ) );
			return dest;
		}
		
		
		public static global::glm.Vec3 fromFloatArray(global::haxe.root.Array<double> arr) {
			unchecked {
				return new global::glm.Vec3(new global::haxe.lang.Null<double>(arr[0], true), new global::haxe.lang.Null<double>(arr[1], true), new global::haxe.lang.Null<double>(arr[2], true));
			}
		}
		
		
		public double x;
		
		public double y;
		
		public double z;
		
		
		
		public double get_r() {
			return this.x;
		}
		
		
		public double set_r(double v) {
			return this.x = v;
		}
		
		
		
		
		public double get_g() {
			return this.y;
		}
		
		
		public double set_g(double v) {
			return this.y = v;
		}
		
		
		
		
		public double get_b() {
			return this.z;
		}
		
		
		public double set_b(double v) {
			return this.z = v;
		}
		
		
		public double @get(int key) {
			unchecked {
				switch (key) {
					case 0:
					{
						return this.x;
					}
					
					
					case 1:
					{
						return this.y;
					}
					
					
					case 2:
					{
						return this.z;
					}
					
					
					default:
					{
						throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Index ", global::haxe.lang.Runtime.toString(key)), " out of bounds (0-2)!"));
					}
					
				}
				
			}
		}
		
		
		public double arrayWrite(int key, double @value) {
			unchecked {
				switch (key) {
					case 0:
					{
						return this.x = @value;
					}
					
					
					case 1:
					{
						return this.y = @value;
					}
					
					
					case 2:
					{
						return this.z = @value;
					}
					
					
					default:
					{
						throw global::haxe.lang.HaxeException.wrap(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("Index ", global::haxe.lang.Runtime.toString(key)), " out of bounds (0-2)!"));
					}
					
				}
				
			}
		}
		
		
		public bool @equals(global::glm.Vec3 b) {
			return  ! ((( ( ( global::System.Math.Abs(((double) (( this.x - b.x )) )) >= global::glm.GLM.EPSILON ) || ( global::System.Math.Abs(((double) (( this.y - b.y )) )) >= global::glm.GLM.EPSILON ) ) || ( global::System.Math.Abs(((double) (( this.z - b.z )) )) >= global::glm.GLM.EPSILON ) ))) ;
		}
		
		
		public string toString() {
			return global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat(global::haxe.lang.Runtime.concat("<", global::haxe.lang.Runtime.toString(this.x)), ", "), global::haxe.lang.Runtime.toString(this.y)), ", "), global::haxe.lang.Runtime.toString(this.z)), ">");
		}
		
		
		public double lengthSquared() {
			return ( ( ( this.x * this.x ) + ( this.y * this.y ) ) + ( this.z * this.z ) );
		}
		
		
		public double length() {
			return global::System.Math.Sqrt(((double) (( ( ( this.x * this.x ) + ( this.y * this.y ) ) + ( this.z * this.z ) )) ));
		}
		
		
		public global::glm.Vec3 subtract(global::glm.Vec3 v) {
			global::glm.Vec3 dest = new global::glm.Vec3(default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>), default(global::haxe.lang.Null<double>));
			dest.x = ( this.x - v.x );
			dest.y = ( this.y - v.y );
			dest.z = ( this.z - v.z );
			return dest;
		}
		
		
		public global::haxe.root.Array<double> toFloatArray() {
			return new global::haxe.root.Array<double>(new double[]{this.x, this.y, this.z});
		}
		
		
		public override double __hx_setField_f(string field, int hash, double @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 98:
					{
						this.set_b(@value);
						return @value;
					}
					
					
					case 103:
					{
						this.set_g(@value);
						return @value;
					}
					
					
					case 114:
					{
						this.set_r(@value);
						return @value;
					}
					
					
					case 122:
					{
						this.z = ((double) (@value) );
						return @value;
					}
					
					
					case 121:
					{
						this.y = ((double) (@value) );
						return @value;
					}
					
					
					case 120:
					{
						this.x = ((double) (@value) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField_f(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_setField(string field, int hash, object @value, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 98:
					{
						this.set_b(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 103:
					{
						this.set_g(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 114:
					{
						this.set_r(((double) (global::haxe.lang.Runtime.toDouble(@value)) ));
						return @value;
					}
					
					
					case 122:
					{
						this.z = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 121:
					{
						this.y = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					case 120:
					{
						this.x = ((double) (global::haxe.lang.Runtime.toDouble(@value)) );
						return @value;
					}
					
					
					default:
					{
						return base.__hx_setField(field, hash, @value, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_getField(string field, int hash, bool throwErrors, bool isCheck, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 1711764408:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toFloatArray", 1711764408)) );
					}
					
					
					case 2014410004:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "subtract", 2014410004)) );
					}
					
					
					case 520590566:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "length", 520590566)) );
					}
					
					
					case 893723873:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "lengthSquared", 893723873)) );
					}
					
					
					case 946786476:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "toString", 946786476)) );
					}
					
					
					case 1072885311:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "equals", 1072885311)) );
					}
					
					
					case 1250329734:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "arrayWrite", 1250329734)) );
					}
					
					
					case 5144726:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get", 5144726)) );
					}
					
					
					case 2049940293:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_b", 2049940293)) );
					}
					
					
					case 291546425:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_b", 291546425)) );
					}
					
					
					case 98:
					{
						return this.get_b();
					}
					
					
					case 2049940298:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_g", 2049940298)) );
					}
					
					
					case 291546430:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_g", 291546430)) );
					}
					
					
					case 103:
					{
						return this.get_g();
					}
					
					
					case 2049940309:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "set_r", 2049940309)) );
					}
					
					
					case 291546441:
					{
						return ((global::haxe.lang.Function) (new global::haxe.lang.Closure(this, "get_r", 291546441)) );
					}
					
					
					case 114:
					{
						return this.get_r();
					}
					
					
					case 122:
					{
						return this.z;
					}
					
					
					case 121:
					{
						return this.y;
					}
					
					
					case 120:
					{
						return this.x;
					}
					
					
					default:
					{
						return base.__hx_getField(field, hash, throwErrors, isCheck, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override double __hx_getField_f(string field, int hash, bool throwErrors, bool handleProperties) {
			unchecked {
				switch (hash) {
					case 98:
					{
						return this.get_b();
					}
					
					
					case 103:
					{
						return this.get_g();
					}
					
					
					case 114:
					{
						return this.get_r();
					}
					
					
					case 122:
					{
						return this.z;
					}
					
					
					case 121:
					{
						return this.y;
					}
					
					
					case 120:
					{
						return this.x;
					}
					
					
					default:
					{
						return base.__hx_getField_f(field, hash, throwErrors, handleProperties);
					}
					
				}
				
			}
		}
		
		
		public override object __hx_invokeField(string field, int hash, global::haxe.root.Array dynargs) {
			unchecked {
				switch (hash) {
					case 1711764408:
					{
						return this.toFloatArray();
					}
					
					
					case 2014410004:
					{
						return this.subtract(((global::glm.Vec3) (dynargs[0]) ));
					}
					
					
					case 520590566:
					{
						return this.length();
					}
					
					
					case 893723873:
					{
						return this.lengthSquared();
					}
					
					
					case 946786476:
					{
						return this.toString();
					}
					
					
					case 1072885311:
					{
						return this.@equals(((global::glm.Vec3) (dynargs[0]) ));
					}
					
					
					case 1250329734:
					{
						return this.arrayWrite(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ), ((double) (global::haxe.lang.Runtime.toDouble(dynargs[1])) ));
					}
					
					
					case 5144726:
					{
						return this.@get(((int) (global::haxe.lang.Runtime.toInt(dynargs[0])) ));
					}
					
					
					case 2049940293:
					{
						return this.set_b(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 291546425:
					{
						return this.get_b();
					}
					
					
					case 2049940298:
					{
						return this.set_g(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 291546430:
					{
						return this.get_g();
					}
					
					
					case 2049940309:
					{
						return this.set_r(((double) (global::haxe.lang.Runtime.toDouble(dynargs[0])) ));
					}
					
					
					case 291546441:
					{
						return this.get_r();
					}
					
					
					default:
					{
						return base.__hx_invokeField(field, hash, dynargs);
					}
					
				}
				
			}
		}
		
		
		public override void __hx_getFields(global::haxe.root.Array<object> baseArr) {
			baseArr.push("b");
			baseArr.push("g");
			baseArr.push("r");
			baseArr.push("z");
			baseArr.push("y");
			baseArr.push("x");
			base.__hx_getFields(baseArr);
		}
		
		
		public override string ToString(){
			return this.toString();
		}
		
		
	}
}


